monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.codecs = [ sbc ]
        bluez5.roles = [ a2dp_sink ]
        bluez5.enable-hw-volume = true
      }
    }
  }
]
